function output_file = plot_ip_ac_fig8_windowed(agent_i,zoom_start)
%PLOT_IP_AC_FIG8_WINDOWED  Two-time-scale diagnostic for online IP-AC.
%
% The 0--30 s view treats each GP update as a new static-average problem:
% it compares the AC error before and after the fixed communication rounds.
% The inset shows the periodic event detector inside one 0.1 s window.
% The lower panel relates the change of P to agent-level broadcasts.

if nargin < 1 || isempty(agent_i), agent_i = 4; end
if nargin < 2 || isempty(zoom_start), zoom_start = 10.0; end

repo_root = fileparts(fileparts(mfilename('fullpath')));
result_folder = fullfile(repo_root,'result','ip_ac_meng_sigma_sweep');
result_file = fullfile(result_folder, ...
    'poe_ac_petc_cache_R10_sigma_0p3_T30.mat');

d = load(result_file,'t_set','ACFixedIterations', ...
    'ACOnlineUpdateInterval','ACPeriodicSigma', ...
    'ac_iteration_count_set','ac_tracking_error_history_set', ...
    'ac_broadcast_count_set','ac_inner_trigger_instance_set', ...
    'ac_trigger_measure_set','ac_trigger_threshold_set', ...
    'projection_absolute_change_rms_set');

update_idx = find(d.ac_iteration_count_set > 0);
window_time = d.t_set(update_idx);
window_count = numel(update_idx);
rounds = d.ACFixedIterations;

start_error = nan(1,window_count);
terminal_error = nan(1,window_count);
for window_i = 1:window_count
    history_i = d.ac_tracking_error_history_set{update_idx(window_i)};
    start_error(window_i) = history_i(1);
    terminal_error(window_i) = history_i(end);
end
remaining_error_ratio = terminal_error./max(start_error,eps);
remaining_error_percent = 100*remaining_error_ratio;

p_change = d.projection_absolute_change_rms_set(update_idx);
broadcasts = d.ac_broadcast_count_set(agent_i,update_idx);

% Choose the update window nearest to the requested zoom time.
[~,zoom_window] = min(abs(window_time-zoom_start));
zoom_index = update_idx(zoom_window);
zoom_t0 = window_time(zoom_window);
round_step = d.ACOnlineUpdateInterval/rounds;
round_time = zoom_t0+(0:rounds-1)*round_step;

detector_error = double(squeeze( ...
    d.ac_trigger_measure_set(agent_i,1:rounds,zoom_index))).^2;
detector_threshold = double(squeeze( ...
    d.ac_trigger_threshold_set(agent_i,1:rounds,zoom_index))).^2;
triggered = logical(squeeze( ...
    d.ac_inner_trigger_instance_set(agent_i,1:rounds,zoom_index)));
zoom_error_history = ...
    d.ac_tracking_error_history_set{zoom_index};
zoom_error_ratio = zoom_error_history/max(zoom_error_history(1),eps);

output_file = fullfile(result_folder, ...
    sprintf('ip_ac_fig8_windowed_agent%d_sigma_0p3_R%d.png', ...
    agent_i,rounds));

fig = figure('Visible','off','Color','w','Position',[60 50 1250 760]);
annotation(fig,'textbox',[0.06 0.945 0.90 0.045], ...
    'String',sprintf(['Windowed IP-AC with periodic event-triggered ' ...
    'broadcasting (sigma = %.1f, R = %d)'],d.ACPeriodicSigma,rounds), ...
    'HorizontalAlignment','center','FontWeight','bold','FontSize',15, ...
    'EdgeColor','none');

%% Full run: the changing reference and actual communication demand.
ax_main = axes(fig,'Position',[0.085 0.57 0.87 0.32]);
hold(ax_main,'on'); grid(ax_main,'on'); box(ax_main,'on');
yyaxis(ax_main,'left');
plot(ax_main,window_time,p_change,'-','Color',[0.12 0.12 0.12], ...
    'LineWidth',1.3);
ylabel(ax_main,'RMS change of P[k]');
yyaxis(ax_main,'right');
bar(ax_main,window_time,broadcasts,0.85, ...
    'FaceColor',[0.78 0.28 0.20],'FaceAlpha',0.34, ...
    'EdgeColor','none');
ylim(ax_main,[-0.2,rounds+0.2]);
yticks(ax_main,0:2:rounds);
ylabel(ax_main,sprintf('Agent %d broadcasts/window',agent_i));
xlim(ax_main,[window_time(1),window_time(end)]);
xlabel(ax_main,'Time (s)');
xline(ax_main,zoom_t0,'--','Color',[0.72 0.08 0.08], ...
    'LineWidth',1.2,'HandleVisibility','off');
title(ax_main,['0--30 s reference change and communication; dashed line ' ...
    'selects the window explained below'],'FontWeight','normal');
mean_reduction = 100*(1-mean(terminal_error)/mean(start_error));
text(ax_main,0.985,0.92,sprintf(['Across all 300 windows: mean AC error ' ...
    '%.2f  ->  %.2f after 10 rounds (%.1f%% reduction)'], ...
    mean(start_error),mean(terminal_error),mean_reduction), ...
    'Units','normalized','HorizontalAlignment','right', ...
    'VerticalAlignment','top','BackgroundColor','w','Margin',3, ...
    'FontSize',9,'Color',[0.10 0.10 0.10]);

%% One representative window: convergence across rounds 0,...,R.
ax_round_error = axes(fig,'Position',[0.085 0.105 0.39 0.34]);
hold(ax_round_error,'on'); grid(ax_round_error,'on'); box(ax_round_error,'on');
plot(ax_round_error,0:rounds,zoom_error_history,'-o', ...
    'Color',[0.08 0.08 0.08],'MarkerFaceColor','w', ...
    'MarkerSize',4,'LineWidth',1.4);
xlim(ax_round_error,[0,rounds]);
xticks(ax_round_error,0:rounds);
xlabel(ax_round_error,'AC round');
ylabel(ax_round_error,'RMS error to current average P');
title(ax_round_error,sprintf(['Selected window %.2f--%.2f s: ' ...
    'what ten AC rounds accomplish'],zoom_t0, ...
    zoom_t0+d.ACOnlineUpdateInterval),'FontWeight','normal');
text(ax_round_error,0.96,0.90,sprintf('%.2f  ->  %.2f\n(%.1f%% reduction)', ...
    zoom_error_history(1),zoom_error_history(end), ...
    100*(1-zoom_error_history(end)/zoom_error_history(1))), ...
    'Units','normalized','HorizontalAlignment','right', ...
    'VerticalAlignment','top','BackgroundColor','w','Margin',3, ...
    'FontSize',9,'Color',[0.55 0.08 0.08]);

%% The same window: literal PETC detector and broadcast rounds.
ax_detector = axes(fig,'Position',[0.56 0.105 0.395 0.34]);
hold(ax_detector,'on'); grid(ax_detector,'on'); box(ax_detector,'on');
round_number = 1:rounds;
stairs(ax_detector,round_number,detector_error,'-', ...
    'Color',[0.12 0.36 0.72],'LineWidth',1.5, ...
    'DisplayName','Broadcast error squared');
stairs(ax_detector,round_number,detector_threshold,'--', ...
    'Color',[0.10 0.55 0.24],'LineWidth',1.3, ...
    'DisplayName','PETC threshold squared');
plot(ax_detector,round_number(triggered),detector_error(triggered),'*', ...
    'Color',[0.82 0.10 0.10],'MarkerSize',9,'LineWidth',1.2, ...
    'DisplayName','Broadcast');
for event_i = find(triggered(:)).'
    plot(ax_detector,[event_i,event_i],[detector_error(event_i),0], ...
        ':','Color',[0.78 0.18 0.18],'LineWidth',0.8, ...
        'HandleVisibility','off');
end
plot(ax_detector,round_number(triggered),zeros(1,nnz(triggered)),'o', ...
    'Color',[0.78 0.18 0.18],'MarkerFaceColor','w', ...
    'MarkerSize',4,'LineWidth',0.8,'HandleVisibility','off');
xlim(ax_detector,[1,rounds]);
xticks(ax_detector,1:rounds);
xlabel(ax_detector,'AC round');
ylabel(ax_detector,'Squared detector value');
title(ax_detector,sprintf(['Same window: trigger decision ' ...
    '(%d broadcasts)'],nnz(triggered)),'FontWeight','normal');
legend(ax_detector,'Location','northeast','Box','off','FontSize',8);

exportgraphics(fig,output_file,'Resolution',200);
savefig(fig,strrep(output_file,'.png','.fig'));
close(fig);

fprintf('Agent %d: %d broadcasts over %d AC windows (mean %.2f/window).\n', ...
    agent_i,sum(broadcasts),window_count,mean(broadcasts));
fprintf('Mean AC RMS error: start %.5g, after R=%d %.5g.\n', ...
    mean(start_error),rounds,mean(terminal_error));
fprintf('Saved %s\n',output_file);
end
