%% Step 1: tune only the DAC tracking termination tolerance
% Fixed: tracking criterion, Kappa_P = 1, epsilon = 0.005.

clear; clc;

ProjectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(ProjectRoot));

ResultFolder = fullfile(ProjectRoot,'control_test','result','Diagnostics');
if ~isfolder(ResultFolder)
    mkdir(ResultFolder);
end

ToleranceSet = [0.005,0.3,0.6,0.85,1.2];
ResultFileSet = { ...
    'control_task_p_and_trigger_current30.mat'; ...
    'control_task_tau_0p3_kappa1_eps0005_30.mat'; ...
    'control_task_tau_0p6_kappa1_eps0005_30.mat'; ...
    'control_task_dac_graft_tracking_tau085_30.mat'; ...
    'control_task_tau_1p2_kappa1_eps0005_30.mat'};

EnvironmentNames = { ...
    'CONTROL_SIM_END_TIME', ...
    'CONTROL_IP_NUM_INDUCING_POINTS', ...
    'CONTROL_DAC_TRIGGER_EPSILON', ...
    'CONTROL_DAC_TRACKING_TOL', ...
    'CONTROL_DAC_CONSENSUS_TOL', ...
    'CONTROL_DAC_TERMINATION_CRITERION', ...
    'CONTROL_DAC_KAPPA_P'};
OldValues = cellfun(@getenv,EnvironmentNames,'UniformOutput',false);
EnvironmentCleanup = onCleanup( ...
    @() restore_environment(EnvironmentNames,OldValues)); %#ok<NASGU>

setenv('CONTROL_SIM_END_TIME','30');
setenv('CONTROL_IP_NUM_INDUCING_POINTS','400');
setenv('CONTROL_DAC_TRIGGER_EPSILON','0.005');
setenv('CONTROL_DAC_CONSENSUS_TOL','0.005');
setenv('CONTROL_DAC_TERMINATION_CRITERION','tracking');
setenv('CONTROL_DAC_KAPPA_P','1');

for ToleranceNr = 1:numel(ToleranceSet)
    ResultPath = fullfile(ResultFolder,ResultFileSet{ToleranceNr});
    if isfile(ResultPath)
        fprintf('Reuse tolerance %.4g: %s\n', ...
            ToleranceSet(ToleranceNr),ResultPath);
        continue;
    end

    setenv('CONTROL_DAC_TRACKING_TOL', ...
        num2str(ToleranceSet(ToleranceNr),16));
    [~,ResultBaseName] = fileparts(ResultFileSet{ToleranceNr});
    fprintf('Run tolerance %.4g ...\n',ToleranceSet(ToleranceNr));
    run_simulation_inducing_point( ...
        'poe',ResultFolder,ResultBaseName,true,0.2,0.1,0,42);
end

%% Four requested metrics
FinalControlTrackingError = zeros(size(ToleranceSet));
TotalBroadcasts = zeros(size(ToleranceSet));
EarlyTriggerMean = zeros(size(ToleranceSet));
LateTriggerMean = zeros(size(ToleranceSet));
ZeroIterationUpdates = zeros(size(ToleranceSet));

for ToleranceNr = 1:numel(ToleranceSet)
    ResultPath = fullfile(ResultFolder,ResultFileSet{ToleranceNr});
    Data = load(ResultPath,'TrackingError_vector', ...
        'dac_event_count_per_agent','DACBroadcastCountPerSecond', ...
        'dac_iteration_count_set','consensus_communication_update_set');

    FinalControlTrackingError(ToleranceNr) = ...
        Data.TrackingError_vector(end);
    TotalBroadcasts(ToleranceNr) = ...
        sum(Data.dac_event_count_per_agent);
    EarlyTriggerMean(ToleranceNr) = ...
        mean(Data.DACBroadcastCountPerSecond(1:5));
    LateTriggerMean(ToleranceNr) = ...
        mean(Data.DACBroadcastCountPerSecond(end-4:end));

    OnlineUpdateMask = ...
        Data.consensus_communication_update_set(1:end-1) > 0;
    ZeroIterationUpdates(ToleranceNr) = sum( ...
        Data.dac_iteration_count_set(OnlineUpdateMask) == 0);
end

SummaryPath = fullfile(ResultFolder, ...
    'control_tracking_tolerance_sweep_summary.md');
FileID = fopen(SummaryPath,'w');
assert(FileID >= 0,'Cannot create tolerance sweep summary.');
FileCleanup = onCleanup(@() fclose(FileID)); %#ok<NASGU>

fprintf(FileID,'# Control-task tracking-tolerance sweep\n\n');
fprintf(FileID,['Fixed settings: tracking criterion, Kappa_P = 1, ', ...
    'epsilon = 0.005, 400 inducing points, 30 s.\n\n']);
fprintf(FileID,['| TrackingTolerance | Final control tracking error | ', ...
    'Total broadcasts | First 5 s trigger mean | ', ...
    'Last 5 s trigger mean | Zero-iteration updates |\n']);
fprintf(FileID,'|---:|---:|---:|---:|---:|---:|\n');
for ToleranceNr = 1:numel(ToleranceSet)
    fprintf(FileID,'| %.4g | %.6g | %.0f | %.6g | %.6g | %.0f |\n', ...
        ToleranceSet(ToleranceNr), ...
        FinalControlTrackingError(ToleranceNr), ...
        TotalBroadcasts(ToleranceNr), ...
        EarlyTriggerMean(ToleranceNr), ...
        LateTriggerMean(ToleranceNr), ...
        ZeroIterationUpdates(ToleranceNr));
end

fprintf('\nTracking-tolerance sweep\n');
fprintf(['Tolerance  FinalControlError  TotalBroadcasts  ', ...
    'EarlyTrigger  LateTrigger  ZeroIterations\n']);
for ToleranceNr = 1:numel(ToleranceSet)
    fprintf('%9.4g  %17.6g  %15.0f  %12.6g  %11.6g  %14.0f\n', ...
        ToleranceSet(ToleranceNr), ...
        FinalControlTrackingError(ToleranceNr), ...
        TotalBroadcasts(ToleranceNr), ...
        EarlyTriggerMean(ToleranceNr), ...
        LateTriggerMean(ToleranceNr), ...
        ZeroIterationUpdates(ToleranceNr));
end
fprintf('Markdown: %s\n',SummaryPath);

function restore_environment(Names,Values)
for EnvironmentNr = 1:numel(Names)
    setenv(Names{EnvironmentNr},Values{EnvironmentNr});
end
end
