function P = gp_masked_poe_init( ...
    LocalGP_set, AgentQuantity, ...
    NumInducingPoints, InducingPoints_Coordinates)
%% compute references signal P
M = NumInducingPoints;
P = zeros(4, AgentQuantity, M);

for AgentNr = 1:AgentQuantity
    for InducingPointIdx = 1:M
        CurrentInducingPoint = InducingPoints_Coordinates ...
        (:,InducingPointIdx);  % 4x1
        
        [mu_n, var_n] = LocalGP_set{AgentNr}.predict ...
        (CurrentInducingPoint);     % 2x1, 2x1
        
        P(1, AgentNr, InducingPointIdx) = ...
                     AgentQuantity * mu_n(1) / var_n(1);
        P(2, AgentNr, InducingPointIdx) = ...
                     AgentQuantity * mu_n(2) / var_n(2);
        P(3, AgentNr, InducingPointIdx) = ...
                     AgentQuantity / var_n(1);
        P(4, AgentNr, InducingPointIdx) = ...
                     AgentQuantity / var_n(2);
    end
end
end
