%% generate_pivot_markdown_table.m
% Generate Markdown pivot tables:
%   ### KIN40K
%   | Level | M | Metric | POE | GPOE | MOE | BCM | RBCM |
%
% It reads the summary CSV generated by plot_inducingpoint_M_tradeoff.m.

clear; clc;

ProjectRoot = fileparts(mfilename('fullpath'));

FigFolder = fullfile(ProjectRoot, 'Result', 'Figures', 'M_ablation_pretty');

summary_csv = fullfile(FigFolder, 'M_ablation_summary_DAC_tr40.csv');

if ~isfile(summary_csv)
    error('Summary CSV not found:\n%s\nRun plot_inducingpoint_M_tradeoff first.', summary_csv);
end

T = readtable(summary_csv);

Dataset_list = {'KIN40K','POL','PUMADYN32NM','SARCOS'};
Method_list  = {'POE','GPOE','MOE','BCM','RBCM'};

M_level_name = {'Low','Medium','High'};
M_level      = [500 1500 2500];

md_path = fullfile(FigFolder, 'M_level_tradeoff_pivot_by_dataset.md');
fid = fopen(md_path, 'w');

fprintf(fid, '# Pivot Low / Medium / High M Trade-off Tables\n\n');
fprintf(fid, 'Averaged over seeds = 1:3. Low = M=500, Medium = M=1500, High = M=2500.\n\n');
fprintf(fid, 'Methods are arranged as columns. Each M level contains Train Time, SMSE, and MSLL rows.\n\n');

for di = 1:numel(Dataset_list)
    dataset = Dataset_list{di};

    fprintf(fid, '### %s\n\n', dataset);
    fprintf(fid, '| Level | M | Metric | POE | GPOE | MOE | BCM | RBCM |\n');
    fprintf(fid, '|---|---:|---|---:|---:|---:|---:|---:|\n');

    for li = 1:numel(M_level)
        level_name = M_level_name{li};
        M = M_level(li);

        time_vals = nan(1, numel(Method_list));
        smse_vals = nan(1, numel(Method_list));
        msll_vals = nan(1, numel(Method_list));

        for ci = 1:numel(Method_list)
            method = Method_list{ci};

            idx = strcmp(T.Dataset, dataset) & ...
                  strcmp(T.Method, method) & ...
                  T.M == M;

            if ~any(idx)
                warning('Missing row: Dataset=%s Method=%s M=%d', dataset, method, M);
                continue;
            end

            time_vals(ci) = T.TrainTime_mspt_mean(idx);
            smse_vals(ci) = T.SMSE_mean(idx);
            msll_vals(ci) = T.MSLL_mean(idx);
        end

        fprintf(fid, '| %s | %d | Train Time | %.4g | %.4g | %.4g | %.4g | %.4g |\n', ...
            level_name, M, ...
            time_vals(1), time_vals(2), time_vals(3), time_vals(4), time_vals(5));

        fprintf(fid, '| %s | %d | SMSE | %.4g | %.4g | %.4g | %.4g | %.4g |\n', ...
            level_name, M, ...
            smse_vals(1), smse_vals(2), smse_vals(3), smse_vals(4), smse_vals(5));

        fprintf(fid, '| %s | %d | MSLL | %.4g | %.4g | %.4g | %.4g | %.4g |\n', ...
            level_name, M, ...
            msll_vals(1), msll_vals(2), msll_vals(3), msll_vals(4), msll_vals(5));
    end

    fprintf(fid, '\n\n');
end

fclose(fid);

fprintf('\nPivot Markdown table saved to:\n%s\n', md_path);